[project]
name = "bibdata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asyncclick>=8.1.8",
    "bib2>=1.5.4",
    "chdb>=4.0.0",
    "click>=8.1",
    "dagster>=1.13.1",
    "fsspec>=2025.5.1",
    "hereutil>=0.1.5",
    "humanize>=4.12.3",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.8",
    "msgspec>=0.19.0",
    "narwhals>=2.10.0",
    "pandas>=2.3.3",
    "polars>=1.35.1",
    "pymarc>=5.3.1",
    "pyspark>=4.1.1",
    "requests>=2.32.3",
    "s3fs>=2025.5.1",
    "sentence-transformers>=5.4.1",
    "sqlglot>=28.1.0",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "dagster-webserver",
    "dagster-dg-cli",
    "pytest>=8.3",
]

[tool.uv]
package = true

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "dagster_assets"
registry_modules = [
    "dagster_assets.components.*",
]
