---
title: Bibdata data space
output:
  html_document:
    toc: yes
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, echo=F, warning=F, error=F, include=F}
knitr::opts_chunk$set(echo=F, warning=F, error=F)
options(box.path = here::here(""))
box::use(src/core)
rlang::env_coalesce(box::topenv(), core)
box::use(src/unified_data)
rlang::env_coalesce(box::topenv(), unified_data)
box::use(src/raw_id_mappings)
rlang::env_coalesce(box::topenv(), raw_id_mappings)
library(tidyverse)
library(gt)
library(glue)
library(gghsci)
library(ggplot2)
library(arrow)
library(here)

p <- scales::label_number()
pp <- scales::label_percent()
```

# Overall summary

## Temporal overview


```{r temporal}
p_year_of_publication |>
  inner_join(e_id, join_by(e_id)) |>
  count(source, year_of_publication) |>
#  union_all(
#    dbnf |> 
#      filter(property=="bnfo:firstYear") |> 
#      inner_join(dbnf |> 
#                   filter(property=="rdf:type", object=="rdafrbr:Manifestation") |> 
#                   distinct(subject)) |> 
#      count(year=object) |>
#      mutate(year=as.integer(year), dataset="dnbf") 
#  ) |>
  mutate(n=as.integer(n)) |>
  filter(year_of_publication >= 1400L,year_of_publication <= 2025L) |>
  ggplot(aes(x=year_of_publication, y=n)) +
  geom_step() +
  theme_hsci_discrete() +
  xlab("Year") +
  ylab("Records (N)") +
  scale_y_continuous(labels=p) +
  scale_x_continuous(breaks=seq(1400,2100, by=100)) +
  facet_wrap(~source, scales="free_y")
```

```{r}
p_years |> 
  inner_join(p_datasets, join_by(between(record_number, min_record_number, max_record_number))) |> 
  left_join(md |> filter(dataset=="hpb", field_code=="009@") |> transmute(record_number, collection=str_c("hpb-", value)), join_by(record_number)) |>
  mutate(dataset=coalesce(collection, dataset)) |>
  count(dataset, year) |>
  mutate(n=as.integer(n)) |>
  filter(year >= 1400L,year <= 2025L) |>
  collect() |>
  complete(dataset,year,fill=list(n=0)) |>
  group_by(dataset) |>
  arrange(year) |>
  #mutate(n=(lag(n)+n+lead(n))/3) |>
  ungroup() |>
  ggplot(aes(x=year, y=n)) +
  geom_line() +
  theme_hsci() +
  scale_color_manual(values=rep(coloropt_pal()(12),10))
  xlab("Year") +
  ylab("Records (N)") +
  scale_y_continuous(labels=p) +
  scale_x_continuous(breaks=seq(1400,2100, by=100)) + facet_wrap(~dataset, scales="free_y")
```


### Records without easily parseable dates between the years 1000 and 2025

```{r}
p_datasets |> 
  mutate(tn=max_record_number-min_record_number + 1) |>
  inner_join(p_years |> 
               inner_join(p_datasets, join_by(between(record_number, min_record_number, max_record_number))) |> 
               distinct(record_number, dataset) |>
               count(dataset)) |>
  transmute(dataset, n=tn-n) |>
  filter(n>0) |>
  collect() |>
  gt(rowname_col="dataset") |>
  fmt_integer()
```


```{r}
language_codes <- ISOcodes::ISO_639_2 |> 
  select(language_code=Alpha_3_B, language=Name) |>
  to_duckdb()

p_languages <- md |> 
  inner_join(formats |> filter(standard=="marc21")) |>
  filter(field_code=="008") |>
  mutate(value=str_sub(value, 36, 38)) |>
  union_all(
    md |> 
      inner_join(formats |> filter(standard=="intermarc")) |>
      filter(field_code=="008") |> 
      mutate(value=str_sub(value, 32, 34))
  ) |>
  union_all(
    md |> 
      inner_join(formats |> filter(standard=="unimarc")) |>
      filter(field_code=="100") |> 
      mutate(value=str_sub(value, 23, 25))
  ) |>
  union_all(
    md |> 
      inner_join(formats |> filter(standard=="pica")) |>
      filter(field_code=="010@", subfield_code=="a")
  ) |>
  union_all(
    md |> 
      inner_join(formats |> filter(standard=="danmarc2")) |>
      filter(field_code=="008", subfield_code=="a")
  ) |>  
  union_all(
    md |> 
      inner_join(formats |> filter(standard=="istc")) |>
      filter(field_code=="date_of_item_single_date")
  ) |>
  rename(language_code=value) |>
  left_join(language_codes, join_by(language_code)) |>
  select(record_number, language_code, language) |>
  compute()
#  transmute(record_number, language=if_else(is.na(language), language_code, str_c(language_code, " (", language, ")")))
```

```{r calculate_dataset_overlap}
t <- p_titles |> 
  inner_join(p_years, join_by(record_number)) |> 
  inner_join(p_datasets, join_by(between(record_number, min_record_number, max_record_number))) |> 
  left_join(d |> 
              filter(dataset=="hpb", field_code=="009@") |> 
              select(record_number, value) |> 
              rename(collection=value)
  ) |>
  mutate(dataset=coalesce(collection, dataset)) |>
  distinct(main_title, year, dataset) |>
  compute()
```

```{r plot_dataset_overlap_absolute}
t |> 
  inner_join(t, join_by(main_title,year)) |> 
  filter(dataset.x!=dataset.y) |> 
  count(dataset.x, dataset.y) |> 
  mutate(n=as.integer(n)) |> 
  filter(n>=1000) |>
  collect() |>
  mutate(dataset.x=fct_infreq(dataset.x)) |>
  mutate(dataset.y=fct_infreq(dataset.y)) |>
  #filter(as.integer(dataset.x) > as.integer(dataset.y)) |>
  mutate(dataset.y=fct_rev(dataset.y)) |>
  ggplot(aes(x=dataset.x,y=dataset.y,label=n,fill=n)) + 
  geom_tile() + 
  theme_hsci() + 
  scale_fill_viridis_c(trans='pseudo_log') + 
  theme(axis.text.x = element_text(angle=90))
```

```{r plot_dataset_overlap_proportional}
t |> 
  inner_join(t, join_by(main_title,year)) |> 
  filter(dataset.x!=dataset.y) |> 
  count(dataset.x, dataset.y) |>
  inner_join(
    t |> count(dataset, name="tn"), join_by(dataset.y==dataset)) |>
  mutate(n=as.integer(n),p=n/tn) |> 
  filter(p>=0.05, dataset.y!="hpb") |>
  collect() |>
  mutate(dataset.x=fct_infreq(dataset.x)) |>
  mutate(dataset.y=fct_infreq(dataset.y)) |>
  #filter(as.integer(dataset.x) > as.integer(dataset.y)) |>
  mutate(dataset.y=fct_rev(dataset.y)) |>
  ggplot(aes(x=dataset.x,y=dataset.y,label=n,fill=p)) + 
  geom_tile() +
  geom_text(aes(label=scales::label_percent(accuracy=1)(p)), color='white') +
  theme_hsci() + 
  scale_fill_viridis_c() + 
  theme(axis.text.x = element_text(angle=90))
```

```{r}
plyd <- p_years |> filter(year>=1800,year<=1900) |> left_join(p_languages) |> left_join(p_countries_of_publication) |> count(year, country_of_publication, language_code) |> collect()
plyd |> 
#  left_join(marc_countries |> 
#              mutate(code=code |> str_remove("-")), join_by(country_of_publication==code)) |>
#  mutate(country_of_publication=coalesce(country, country_of_publication)) |>
  mutate(decade=10*floor(year/10), country_of_publication=country_of_publication |> fct_lump_n(24,w = n), language=language |> fct_lump_n(12, w=n),n=as.integer(n)) |> 
  group_by(country_of_publication,decade,language) |> 
  summarise(n=sum(n), .groups="drop") |> 
  ggplot(aes(x=decade,y=n, fill=language)) + 
  facet_wrap(~country_of_publication) + 
  theme_hsci_discrete() + 
  geom_area(position='fill')
```

