---
title: Bibdata data space
output:
  html_document:
    toc: yes
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, echo=F, warning=F, error=F, include=F}
knitr::opts_chunk$set(echo=F, warning=F, error=F)
library(tidyverse)
library(gt)
library(glue)
library(gghsci)
library(ggplot2)
library(arrow)
library(here)

p <- scales::label_number()
pp <- scales::label_percent()

if (is.null(getOption("arrow_duck_con"))) {
  options(
    arrow_duck_con = DBI::dbConnect(
      duckdb::duckdb(bigint = "integer64"),
      bigint = "integer64",
      dbdir = str_c(tempdir(), "/duckdb")
    )
  )
}
con <- getOption("arrow_duck_con")

DBI::dbExecute(con, "SET preserve_insertion_order = false;")
DBI::dbExecute(con, "SET memory_limit = '64GB';")

formats <- read_tsv(here("data/schema-info/collection_info.tsv")) |> 
  to_duckdb()

td <- NULL
md <- NULL
max_record_number <- 0L

formats |> 
  collect() |>
  rowwise() |>
  group_walk(\(row, ...) {
    if (row$dataset == "wikidata") {
      list.files(here("data/wikidata/")) |> 
        str_replace("(_[0-9])*\\.parquet","") |> 
        unique() |>
        walk(\(name) .GlobalEnv[[str_c('wd_',name)]] <- tbl(con, glue::glue("read_parquet('{here('data/wikidata')}/{name}*.parquet')")))
      NULL
    } else if (row$dataset == "isni") {
      list.files(here("data/isni/")) |> 
        str_replace("(_[0-9])*\\.parquet","") |> 
        unique() |>
        walk(\(name) .GlobalEnv[[str_c('isni_',name)]] <- tbl(con, glue::glue("read_parquet('{here('data/isni')}/{name}*.parquet')")))
    } else if (row$dataset == "geonames") {
      .GlobalEnv[["geonames"]] <- tbl(con, glue::glue("read_parquet('{here('data')}/geonames/geonames*.parquet')"))
      .GlobalEnv[["geonames_alternate_names"]] <- tbl(con, glue::glue("read_parquet('{here('data')}/geonames/alternate_names*.parquet')"))
    } else if (row$standard == "rdf") {
      ds <- tbl(con, glue::glue("read_parquet('{here('data')}/{row$dataset}/{row$dataset}*.parquet')")) |>
        relocate(subject, property, object)
      .GlobalEnv[[row$dataset]] <- ds
      ds <- ds |> 
        mutate(dataset=row$dataset)
      if (is.null(.GlobalEnv[['td']]))
        .GlobalEnv[['td']] <- ds
      else
        .GlobalEnv[['td']] <- .GlobalEnv[['td']] |> 
          union_all(ds)
    } else if (row$standard %in% c("intermarc", "marc21", "unimarc", "pica", "istc")) {
      ds <- tbl(con, glue::glue("read_parquet('{here('data')}/{row$dataset}/{row$dataset}*.parquet')"))
      .GlobalEnv[[row$dataset]] <- ds
      if (ds |> head(n=1) |> count() |> pull() == 0) print(glue::glue("Dataset {row$dataset} is empty."))
      else {
        if (is.null(.GlobalEnv[['md']])) {
          .GlobalEnv[['md']] <- ds |> 
            mutate(dataset=row$dataset)
          .GlobalEnv[['max_record_number']] <- ds |> 
            summarise(max(record_number)) |> 
            pull()        
        } else 
          max_record_number <- .GlobalEnv[['max_record_number']]
        ds <- ds |> 
          mutate(dataset=row$dataset, record_number = max_record_number + record_number)
        .GlobalEnv[['md']] <- .GlobalEnv[['md']] |>
          union_all(ds)
        .GlobalEnv[['max_record_number']] <- ds |> 
          summarise(max(record_number)) |> 
          pull()
      }
    } else {
      stop("Unknown dataset type ", row)
    }
  })
```

# Overall summary

`r d |> distinct(record_number) |> count() |> pull() |> as.integer() |> p()` records and `r d |> count() |> pull() |> as.integer() |> p()` attribute values in total. Constituent files:

```{r filelist, results = 'asis'}

cat("\n\n")
for (file in files[order(files |> str_replace(".parquet", ""))]) {
  unit_size <- unit_print(fs::file_info(file)$size)
  cat(glue::glue("- {file} ({unit_size})\n"))
}
cat("\n")
```

```{r}
p_titles <- md |> 
  inner_join(formats |> filter(standard =="marc21")) |>
  filter(field_code=="245", subfield_code=="a") |>
  union_all(md |> 
              inner_join(formats |> filter(standard=="intermarc")) |>
              filter(field_code=="245", subfield_code=="a")
  ) |>
  union_all(md |> 
              inner_join(formats |> filter(standard=="unimarc")) |>
              filter(field_code=="200", subfield_code=="a")
  ) |>
  union_all(md |> 
              inner_join(formats |> filter(standard=="pica")) |>
              filter(field_code=="021A", subfield_code=="a")
  ) |>
  union_all(md |> 
              inner_join(formats |> filter(standard=="istc")) |>
              filter(field_code=="title")
  ) |>
  select(record_number, main_title=value) |>
  compute()
```

```{r}
p_countries_of_publication <- md |> 
  inner_join(formats |> filter(standard=="marc21")) |>
  filter(field_code=="008") |> 
  mutate(value=value |> str_sub(16, 18) |> str_squish()) |>
  union_all(md |> 
    inner_join(formats |> filter(standard=="marc21")) |>
    filter(field_code=="044")
  ) |>
   union_all(
    md |> 
      inner_join(formats |> filter(standard=="intermarc")) |>
      filter(field_code=="008") |> 
      mutate(value=str_sub(value, 30, 31))
  ) |>
  union_all(
    md |> 
      inner_join(formats |> filter(standard=="unimarc")) |>
      filter(field_code=="102", subfield_code=="a") 
  ) |>
  union_all(
    md |> 
      inner_join(formats |> filter(standard=="pica")) |>
      filter(field_code=="019@", subfield_code=="a")
  ) |>
  union_all(
    md |> 
      inner_join(formats |> filter(standard=="istc")) |>
      filter(subfield_code=="geo_info_imprint_country_code")
  ) |>
  mutate(value=value |> str_replace("[^-]*-", "") |> str_replace("-.*","") |> str_to_lower()) |>
  distinct(record_number, country_of_publication=value) |>
  compute()
p_countries_of_publication
```



```{r}
p_datasets <- md |> 
  group_by(dataset) |> 
  summarise(min_record_number=min(record_number),max_record_number=max(record_number)) |>
  compute()
```


## Temporal overview

```{r temporal}
p_years <- md |> 
  inner_join(formats |> filter(standard=="marc21")) |>
  filter(field_code=="008") |> 
  mutate(value=str_sub(value, 8, 11)) |> 
  union_all(
    md |> 
      inner_join(formats |> filter(standard=="intermarc")) |>
      filter(field_code=="008") |> 
      mutate(value=str_sub(value, 9, 12))
  ) |>
  union_all(
    md |> 
      inner_join(formats |> filter(standard=="unimarc")) |>
      filter(field_code=="100") |> 
      mutate(value=str_sub(value, 10, 13))
  ) |>
  union_all(
    md |> 
      inner_join(formats |> filter(standard=="pica")) |>
      filter(field_code=="011@")
  ) |>
  union_all(
    md |> 
      inner_join(formats |> filter(standard=="istc")) |>
      filter(field_code=="date_of_item_single_date")
  ) |>
#  union_all(md |>
#    filter(dataset=="viaf", field_code=="997") |>
#    mutate(value=str_sub(value, 1, 5))
#  ) |>
  filter(str_detect(value, "^\\d{1,4}$")) |>
  mutate(year=as.integer(value)) |>
  select(record_number, year) |>
  compute()
```


```{r temporal}
p_years |>
  count(dataset, year) |>
  mutate(n=as.integer(n)) |>
  filter(year >= 1400L,year <= 2025L) |>
  ggplot(aes(x=year, y=n)) +
  geom_step() +
  theme_hsci_discrete() +
  xlab("Year") +
  ylab("Records (N)") +
  scale_y_continuous(labels=p) +
  scale_x_continuous(breaks=seq(1400,2100, by=100)) +
  facet_wrap(~dataset, scales="free_y")
```

```{r}
p_years |> 
  inner_join(p_datasets, join_by(between(record_number, min_record_number, max_record_number))) |> 
  left_join(d |> filter(dataset=="hpb", field_code=="009@") |> select(record_number, value) |> rename(collection=value)) |>
  mutate(dataset=coalesce(collection,dataset)) |>
  filter(dataset!="hpb") |>
  count(dataset, year) |>
  mutate(n=as.integer(n)) |>
  filter(year >= 1400L,year <= 2025L) |>
  collect() |>
  complete(dataset,year,fill=list(n=0)) |>
  group_by(dataset) |>
  arrange(year) |>
  #mutate(n=(lag(n)+n+lead(n))/3) |>
  ungroup() |>
  ggplot(aes(x=year, y=n)) +
  geom_line() +
  theme_hsci_discrete() +
  xlab("Year") +
  ylab("Records (N)") +
  scale_y_continuous(labels=p) +
  scale_x_continuous(breaks=seq(1400,2100, by=100)) + facet_wrap(~dataset, scales="free_y")
```


### Records without easily parseable dates between the years 1000 and 2025

```{r}
p_datasets |> 
  mutate(tn=max_record_number-min_record_number + 1) |>
  inner_join(p_years |> 
               inner_join(p_datasets, join_by(between(record_number, min_record_number, max_record_number))) |> 
               distinct(record_number, dataset) |>
               count(dataset)) |>
  transmute(dataset, n=tn-n) |>
  filter(n>0) |>
  collect() |>
  gt(rowname_col="dataset") |>
  fmt_integer()
```


```{r}
language_codes <- ISOcodes::ISO_639_2 |> 
  select(language_code=Alpha_3_B, language=Name) |>
  to_duckdb()

p_languages <- md |> 
  inner_join(formats |> filter(standard=="marc21")) |>
  filter(field_code=="008") |>
  mutate(value=str_sub(value, 36, 38)) |>
  union_all(
    md |> 
      inner_join(formats |> filter(standard=="intermarc")) |>
      filter(field_code=="008") |> 
      mutate(value=str_sub(value, 32, 34))
  ) |>
  union_all(
    md |> 
      inner_join(formats |> filter(standard=="unimarc")) |>
      filter(field_code=="100") |> 
      mutate(value=str_sub(value, 23, 25))
  ) |>
  union_all(
    md |> 
      inner_join(formats |> filter(standard=="pica")) |>
      filter(field_code=="010@", subfield_code=="a")
  ) |>
  union_all(
    md |> 
      inner_join(formats |> filter(standard=="istc")) |>
      filter(field_code=="date_of_item_single_date")
  ) |>
  rename(language_code=value) |>
  left_join(language_codes, join_by(language_code)) |>
  select(record_number, language_code, language) |>
  compute()
#  transmute(record_number, language=if_else(is.na(language), language_code, str_c(language_code, " (", language, ")")))
```

```{r calculate_dataset_overlap}
t <- p_titles |> 
  inner_join(p_years, join_by(record_number)) |> 
  inner_join(p_datasets, join_by(between(record_number, min_record_number, max_record_number))) |> 
  left_join(d |> 
              filter(dataset=="hpb", field_code=="009@") |> 
              select(record_number, value) |> 
              rename(collection=value)
  ) |>
  mutate(dataset=coalesce(collection, dataset)) |>
  distinct(main_title, year, dataset) |>
  compute()
```

```{r plot_dataset_overlap_absolute}
t |> 
  inner_join(t, join_by(main_title,year)) |> 
  filter(dataset.x!=dataset.y) |> 
  count(dataset.x, dataset.y) |> 
  mutate(n=as.integer(n)) |> 
  filter(n>=1000) |>
  collect() |>
  mutate(dataset.x=fct_infreq(dataset.x)) |>
  mutate(dataset.y=fct_infreq(dataset.y)) |>
  #filter(as.integer(dataset.x) > as.integer(dataset.y)) |>
  mutate(dataset.y=fct_rev(dataset.y)) |>
  ggplot(aes(x=dataset.x,y=dataset.y,label=n,fill=n)) + 
  geom_tile() + 
  theme_hsci() + 
  scale_fill_viridis_c(trans='pseudo_log') + 
  theme(axis.text.x = element_text(angle=90))
```

```{r plot_dataset_overlap_proportional}
t |> 
  inner_join(t, join_by(main_title,year)) |> 
  filter(dataset.x!=dataset.y) |> 
  count(dataset.x, dataset.y) |>
  inner_join(
    t |> count(dataset, name="tn"), join_by(dataset.y==dataset)) |>
  mutate(n=as.integer(n),p=n/tn) |> 
  filter(p>=0.05, dataset.y!="hpb") |>
  collect() |>
  mutate(dataset.x=fct_infreq(dataset.x)) |>
  mutate(dataset.y=fct_infreq(dataset.y)) |>
  #filter(as.integer(dataset.x) > as.integer(dataset.y)) |>
  mutate(dataset.y=fct_rev(dataset.y)) |>
  ggplot(aes(x=dataset.x,y=dataset.y,label=n,fill=p)) + 
  geom_tile() +
  geom_text(aes(label=scales::label_percent(accuracy=1)(p)), color='white') +
  theme_hsci() + 
  scale_fill_viridis_c() + 
  theme(axis.text.x = element_text(angle=90))
```

```{r}
plyd |> 
  filter(year >= 1400L,year <= 2025L) |> 
#  left_join(marc_countries |> 
#              mutate(code=code |> str_remove("-")), join_by(country_of_publication==code)) |>
#  mutate(country_of_publication=coalesce(country, country_of_publication)) |>
  mutate(decade=10*floor(year/10), country_of_publication=country_of_publication |> fct_lump_n(24,w = n), language=language |> fct_lump_n(12, w=n),n=as.integer(n)) |> 
  group_by(country_of_publication,decade,language) |> 
  summarise(n=sum(n), .groups="drop") |> 
  ggplot(aes(x=decade,y=n, fill=language)) + 
  facet_wrap(~country_of_publication) + 
  theme_hsci_discrete() + 
  geom_area(position='fill')
```

